version: "3.8"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    # ports:
    #   - "5672:5672"
    #   - "15672:15672"
    networks:
      - app-network
  worker:
    image: "docker-python-sandbox-supervisor-worker:latest"
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
  supervisor:
    image: "docker-python-sandbox-supervisor:latest"
    depends_on:
      - rabbitmq
      - worker
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    networks:
      - app-network
  app:
    image: "code-interpreter-lite:latest"
    depends_on:
      - rabbitmq
      - worker
      - supervisor
    ports:
      - "7860:7860"
    env_file:
      - .env
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
